### ISSUE TITLE
New command line options with argparse

### ISSUE THREAD

**Issue by lwpulsifer** [MattiooFR/log-maker-100-days#2]
- [x] `-o` for overwriting the given filename (i.e. if `log.md` exists, it is overwritten instead of an error being thrown)
- [x] `-f` for choosing a file name to write to 
- [x] `-l` for appending to a list of logs (i.e. if `log.md` exists, writes to `log1.md`; if `log1.md` exists, writes to `log2.md`, etc.)
- [x] `-d` for duration of the challenge (100 as default, of course)

**Comment by MattiooFR** [comment]
I just pushed a version with the duration argument done ! I'm working on the other :)

**Comment by lwpulsifer** [comment]
Cool! I have a couple of them written, but I'm still having issues with trying to work with your repo. Check my Slack dm for more info.

**Comment by MattiooFR** [comment]
I replied on slack, I changed the option now pull request are available to anyone !
I also have done the filename argument feat.
